package org.openapitools.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.Valid;
import javax.validation.constraints.*;

/**
 * Product
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2018-10-15T15:19:21.557+02:00[Europe/Rome]")

public class Product   {
  @JsonProperty("accountCodeAutoGenerated")
  private Boolean accountCodeAutoGenerated = null;

  @JsonProperty("accountCodeRequired")
  private Boolean accountCodeRequired = null;

  @JsonProperty("apportionByContract")
  private Boolean apportionByContract = null;

  @JsonProperty("distributorId")
  private Long distributorId = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("portfolioExternalData")
  private Boolean portfolioExternalData = null;

  public Product accountCodeAutoGenerated(Boolean accountCodeAutoGenerated) {
    this.accountCodeAutoGenerated = accountCodeAutoGenerated;
    return this;
  }

  /**
   * Indicates whether the Asset Account Code and/or the Current Account Code will be autogenerated by the system.
   * @return accountCodeAutoGenerated
  **/
  @ApiModelProperty(value = "Indicates whether the Asset Account Code and/or the Current Account Code will be autogenerated by the system.")


  public Boolean getAccountCodeAutoGenerated() {
    return accountCodeAutoGenerated;
  }

  public void setAccountCodeAutoGenerated(Boolean accountCodeAutoGenerated) {
    this.accountCodeAutoGenerated = accountCodeAutoGenerated;
  }

  public Product accountCodeRequired(Boolean accountCodeRequired) {
    this.accountCodeRequired = accountCodeRequired;
    return this;
  }

  /**
   * Indicates whether the Asset Account Code and/or the Current Account Code are mandatory.
   * @return accountCodeRequired
  **/
  @ApiModelProperty(value = "Indicates whether the Asset Account Code and/or the Current Account Code are mandatory.")


  public Boolean getAccountCodeRequired() {
    return accountCodeRequired;
  }

  public void setAccountCodeRequired(Boolean accountCodeRequired) {
    this.accountCodeRequired = accountCodeRequired;
  }

  public Product apportionByContract(Boolean apportionByContract) {
    this.apportionByContract = apportionByContract;
    return this;
  }

  /**
   * Indicates whether the product do apportions by contract
   * @return apportionByContract
  **/
  @ApiModelProperty(value = "Indicates whether the product do apportions by contract")


  public Boolean getApportionByContract() {
    return apportionByContract;
  }

  public void setApportionByContract(Boolean apportionByContract) {
    this.apportionByContract = apportionByContract;
  }

  public Product distributorId(Long distributorId) {
    this.distributorId = distributorId;
    return this;
  }

  /**
   * The Id of the {Distributor} associated to the Product
   * @return distributorId
  **/
  @ApiModelProperty(value = "The Id of the {Distributor} associated to the Product")


  public Long getDistributorId() {
    return distributorId;
  }

  public void setDistributorId(Long distributorId) {
    this.distributorId = distributorId;
  }

  public Product id(Long id) {
    this.id = id;
    return this;
  }

  /**
   * Product Id
   * @return id
  **/
  @ApiModelProperty(value = "Product Id")


  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Product name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Product name
   * @return name
  **/
  @ApiModelProperty(value = "Product name")


  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Product portfolioExternalData(Boolean portfolioExternalData) {
    this.portfolioExternalData = portfolioExternalData;
    return this;
  }

  /**
   * Indicates whether the product is associated to a portfolio which data is provided by external entities
   * @return portfolioExternalData
  **/
  @ApiModelProperty(value = "Indicates whether the product is associated to a portfolio which data is provided by external entities")


  public Boolean getPortfolioExternalData() {
    return portfolioExternalData;
  }

  public void setPortfolioExternalData(Boolean portfolioExternalData) {
    this.portfolioExternalData = portfolioExternalData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Product product = (Product) o;
    return Objects.equals(this.accountCodeAutoGenerated, product.accountCodeAutoGenerated) &&
        Objects.equals(this.accountCodeRequired, product.accountCodeRequired) &&
        Objects.equals(this.apportionByContract, product.apportionByContract) &&
        Objects.equals(this.distributorId, product.distributorId) &&
        Objects.equals(this.id, product.id) &&
        Objects.equals(this.name, product.name) &&
        Objects.equals(this.portfolioExternalData, product.portfolioExternalData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountCodeAutoGenerated, accountCodeRequired, apportionByContract, distributorId, id, name, portfolioExternalData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Product {\n");
    
    sb.append("    accountCodeAutoGenerated: ").append(toIndentedString(accountCodeAutoGenerated)).append("\n");
    sb.append("    accountCodeRequired: ").append(toIndentedString(accountCodeRequired)).append("\n");
    sb.append("    apportionByContract: ").append(toIndentedString(apportionByContract)).append("\n");
    sb.append("    distributorId: ").append(toIndentedString(distributorId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    portfolioExternalData: ").append(toIndentedString(portfolioExternalData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

