/**
 * MMC - Backend API
 * Motore di messaggistica API
 *
 * OpenAPI spec version: 0.3.0
 * Contact: d.ghilardi@reply.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

import io.swagger.server.models.MessageModel
import io.swagger.server.models.ResultModel


/**
 *
 * @param result
 * @param messages */
data class CheckMessageResponse(
        val result: ResultModel? = null,
        val messages: kotlin.Array<MessageModel>? = null
) {

}


