/**
 * MMC - Backend API
 * Motore di messaggistica API
 *
 * OpenAPI spec version: 0.3.0
 * Contact: d.ghilardi@reply.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

import io.swagger.server.models.AttachmentModel
import io.swagger.server.models.MessageContentModel
import io.swagger.server.models.RecipientModel
import io.swagger.server.models.SenderModel


/**
 *
 * @param priority priority of the message
 * @param type Represents the message type
 * @param from
 * @param to
 * @param content
 * @param attachments */
data class SendMessageRequest(
        /* priority of the message */

        val priority: java.math.BigDecimal,
        /* Represents the message type */

        val type: SendMessageRequest.Type,
        val from: SenderModel,
        val to: kotlin.Array<RecipientModel>,
        val content: MessageContentModel,
        val attachments: kotlin.Array<AttachmentModel>
) {

    /**
     * Represents the message type
     * Values: email,sms,push
     */
    enum class Type(val value: kotlin.String) {

        email("email"),

        sms("sms"),

        push("push");

    }

}


