= Design Pattern in Java image:https://github.com/rinaudosal/designpatterns/workflows/build/badge.svg["build"] image:.github/badges/jacoco.svg["Coverage"]

Repository providing a useful content with most of the popular design pattern.
Are implemented any examples of the most popular design pattern and For each use case has provided how to test it.

You can use this project for free use, feel free to integrate it or send a pull request or feedback!

The examples and usages in Java Examples are inspired from https://app.pluralsight.com/profile/author/bryan-hansen[Bryan Hansen] courses on Pluralsight

To run the test after uploading the repo try this:
----
	mvn clean verify
----

For each design pattern are described the following consideration:

* Short description
* Implementation in Java API

== Behavioural Patterns

Behavioral Patterns are concerned with providing solutions regarding object interaction
- how they communicate, how are some dependent on others, and how to segregate them to be both dependent and independent and provide both flexibility and testing capabilities.

=== Chain of Responsibility
This pattern is useful when we want decouple Sender and Receiver.
The Sender don't know who execute the operation sent, the receiver don't know who has call them.
The Sender invoke an Handler where the chain has builded and only him know how the chain is builded.
Each element of the chain extends a common abstract class.

Examples:

* java.util.logging.Logger#log
* javax.servlet.Filter#doFilter
* Spring Security Filter Chain

=== Interpreter

It's one of the most difficult pattern to implement and it's related to the grammar expressions.
The interpreter interpret the messages received based on the proper logic itself
Main actor of the pattern are [I]
Gli attori principali del pattern sono:
Interfaccia Interpreter implementata da tutti i ConcreteInterpreter
Metodo interpret dell'interfaccia che riceve in input il messaggio da interpretare
costruttore del ConcreteInterpreter con l'inizializzazione degli elementi necessari all'interpretazione Classe Handler che costruisce la logica di interpretazione dell'elemento

Examples:

* java.regex.Pattern

== Creational Patterns

Creational design patterns are concerned with the way of creating objects.
These design patterns are used when a decision must be made at the time of instantiation of a class (i.e. creating an object of a class). But everyone knows an object is created by using new keyword in java.

== Structural Patterns

Structural design patterns are concerned with how classes and objects can be composed, to form larger structures.
The structural design patterns simplifies the structure by identifying the relationships.
These patterns focus on, how the classes inherit from each other and how they are composed from other classes.
[source,bash,indent=0]


== License
Design Pattern project is Open Source software released under the
https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
