= Design Pattern in Java
:github: https://github.com/spring-projects/spring-boot

Repository providing an useful content with most of the popular design pattern.
Are implemented any examples of the most popular design pattern and For each use case has provided how to test it.

You can use this project for free use, feel free to integrate it or send a pull request or feedback!

To run the test after uploading the repo try this:
----
	mvn clean verify
----

For each design pattern are described the following consideration:

* Short description
* Implementation in Java API
* Consideration

== Behavioural Patterns

Behavioral Patterns are concerned with providing solutions regarding object interaction
- how they communicate, how are some dependent on others, and how to segregate them to be both dependent and independent and provide both flexibility and testing capabilities.

=== Chain of Responsability

This pattern is useful when we want decouple Sender and Receiver.
The Sender don't know who execute the operation sent, the receiver don't know who has call them.
The Sender invoke an Handler where the chain has builded and only him know how the chain is builded.
Each element of the chain extends a common abstract class.

Examples:

* java.util.logging.Logger#log
* javax.servlet.Filter#doFilter
* Spring Security Filter Chain

=== Interpreter

It's one of the most difficult pattern to implement and it's related to the grammar expressions.
The interpreter interpret the messages received based on the proper logic itself
Main actor of the pattern are [I]
Gli attori principali del pattern sono:
Interfaccia Interpreter implementata da tutti i ConcreteInterpreter
Metodo interpret dell'interfaccia che riceve in input il messaggio da interpretare
costruttore del ConcreteInterpreter con l'inizializzazione degli elementi necessari all'interpretazione Classe Handler che costruisce la logica di interpretazione dell'elemento

Examples:

* java.regex.Pattern

== Creational Patterns

Creational design patterns are concerned with the way of creating objects.
These design patterns are used when a decision must be made at the time of instantiation of a class (i.e. creating an object of a class). But everyone knows an object is created by using new keyword in java.

== Structural Patterns

Structural design patterns are concerned with how classes and objects can be composed, to form larger structures.
The structural design patterns simplifies the structure by identifying the relationships.
These patterns focus on, how the classes inherit from each other and how they are composed from other classes.
[source,bash,indent=0]


== Getting help
Having trouble with Design Pattern? We'd like to help!

* Ask a question - we monitor https://stackoverflow.com[stackoverflow.com] for questions
  tagged with https://stackoverflow.com/tags/spring-boot[`spring-boot`]. You can also chat
  with the community on https://gitter.im/spring-projects/spring-boot[Gitter].
* Report bugs with Spring Boot at {github}/issues[github.com/spring-projects/spring-boot/issues].



== Reporting Issues
Spring Boot uses GitHub's integrated issue tracking system to record bugs and feature
requests. If you want to raise an issue, please follow the recommendations below:

* Before you log a bug, please search the {github}/issues[issue tracker] to see if someone
  has already reported the problem.
* If the issue doesn't already exist, {github}/issues/new[create a new issue].
* Please provide as much information as possible with the issue report, we like to know
  the version of Spring Boot that you are using, as well as your Operating System and
  JVM version.
* If you need to paste code, or include a stack trace use Markdown +++```+++ escapes
  before and after your text.
* If possible try to create a test-case or project that replicates the problem and attach
  it to the issue.



== Building from Source
You don't need to build from source to use Spring Boot (binaries in
https://repo.spring.io[repo.spring.io]), but if you want to try out the latest and
greatest, Spring Boot can be built and published to your local Maven cache using the
https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle wrapper]. You also
need JDK 1.8.

[indent=0]
----
	$ ./gradlew publishToMavenLocal
----

This will build all of the jars and documentation and publish them to your local
Maven cache. It won't run any of the tests. If you want to build everything, use the
`build` task:

[indent=0]
----
	$ ./gradlew build
----

== Modules
There are a number of modules in Spring Boot, here is a quick overview:



=== spring-boot
The main library providing features that support the other parts of Spring Boot,
these include:

* The `SpringApplication` class, providing static convenience methods that can be used
to write a stand-alone Spring Application. Its sole job is to create and refresh an
appropriate Spring `ApplicationContext`
* Embedded web applications with a choice of container (Tomcat, Jetty or Undertow)
* First class externalized configuration support
* Convenience `ApplicationContext` initializers, including support for sensible logging
defaults

== License
Design Pattern project is Open Source software released under the
https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
