/**
 * MMC - Backend API
 * Motore di messaggistica API
 *
 * OpenAPI spec version: 0.3.0
 * Contact: d.ghilardi@reply.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 *
 * @param resultCode result code
 * @param resultDescription result description*/
data class ErrorResponse(
        /* result code */
        val resultCode: kotlin.String? = null,
        /* result description */
        val resultDescription: kotlin.String? = null
) {

}


