/**
* MMC - Backend API
* Motore di messaggistica API
*
* OpenAPI spec version: 0.3.0
* Contact: d.ghilardi@reply.it
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.server.models






/**
 *  
 * @param code  
 * @param description */
data class ResultModel (
    val code: ResultModel.Code? = null,
    val description: kotlin.String? = null
) {

    /**
    * 
    * Values: 0
    */
    enum class Code(val value: kotlin.String){
    
        0("0");
    
    }

}


