/**
* MMC - Backend API
* Motore di messaggistica API
*
* OpenAPI spec version: 0.3.0
* Contact: d.ghilardi@reply.it
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.server.models






/**
 *  
 * @param resultCode  
 * @param resultDescription  
 * @param uuid unique identifier of the message*/
data class SendResponse (
    val resultCode: SendResponse.ResultCode? = null,
    val resultDescription: kotlin.String? = null,
    /* unique identifier of the message */
    val uuid: kotlin.String? = null
) {

    /**
    * 
    * Values: 0
    */
    enum class ResultCode(val value: kotlin.String){
    
        0("0");
    
    }

}


