/**
* MMC - Backend API
* Motore di messaggistica API
*
* OpenAPI spec version: 0.3.0
* Contact: d.ghilardi@reply.it
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.server.models






/**
 *  
 * @param name sender name 
 * @param surname sender surname 
 * @param alias alternative sender name 
 * @param reference digital reference of the sender, could be the telephone number for sms messages, email address for email messages*/
data class SenderModel (
    /* digital reference of the sender, could be the telephone number for sms messages, email address for email messages */

    val reference: kotlin.String,
    /* sender name */
    val name: kotlin.String? = null,
    /* sender surname */
    val surname: kotlin.String? = null,
    /* alternative sender name */
    val alias: kotlin.String? = null
) {

}


