/**
* MMC - Backend API
* Motore di messaggistica API
*
* OpenAPI spec version: 0.3.0
* Contact: d.ghilardi@reply.it
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.server.models






/**
 *  
 * @param resultCode Outcome code * -100 - missing mandatory fields * -101 - format error * -102 - non processable parameters * -110 - device id not found * -111 - app code not found * -112 - message id not found * -113 - message uuid not found  
 * @param resultDescription error description*/
data class UnprocessableEntityResponse (
    /* Outcome code * -100 - missing mandatory fields * -101 - format error * -102 - non processable parameters * -110 - device id not found * -111 - app code not found * -112 - message id not found * -113 - message uuid not found  */
    val resultCode: UnprocessableEntityResponse.ResultCode? = null,
    /* error description */
    val resultDescription: kotlin.String? = null
) {

    /**
    * Outcome code * -100 - missing mandatory fields * -101 - format error * -102 - non processable parameters * -110 - device id not found * -111 - app code not found * -112 - message id not found * -113 - message uuid not found 
    * Values: 100,101,102,110,111,112,113
    */
    enum class ResultCode(val value: kotlin.String){
    
        100("-100"),
    
        101("-101"),
    
        102("-102"),
    
        110("-110"),
    
        111("-111"),
    
        112("-112"),
    
        113("-113");
    
    }

}


