/**
 * MMC - Backend API
 * Motore di messaggistica API
 *
 * OpenAPI spec version: 0.3.0
 * Contact: d.ghilardi@reply.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.apis

// ktor 0.9.x is missing io.ktor.locations.DELETE, this adds it.
// see https://github.com/ktorio/ktor/issues/288

import com.google.gson.Gson
import io.ktor.application.call
import io.ktor.http.HttpStatusCode
import io.ktor.locations.get
import io.ktor.request.receive
import io.ktor.response.respond
import io.ktor.routing.Route
import io.ktor.routing.post
import io.ktor.routing.route
import io.swagger.server.Paths
import io.swagger.server.delete
import io.swagger.server.models.SendMessageRequest
import org.slf4j.LoggerFactory


fun Route.DefaultApi() {

    val gson = Gson()
    val empty = mutableMapOf<String, Any?>()
    val logger = LoggerFactory.getLogger("defaultAPi")

    route("/management/device") {
        post {
            call.respond(HttpStatusCode.NotImplemented)
        }
    }

    delete<Paths.deleteDevice> { it: Paths.deleteDevice -> call.respond(HttpStatusCode.NotImplemented) }

    get<Paths.messageCheck> { it: Paths.messageCheck -> call.respond(HttpStatusCode.NotImplemented) }

    route("/message/send") {
        post {

            val sendMessageRequest = call.receive<SendMessageRequest>()
            logger.info("Sending message {}", sendMessageRequest)

            call.respond(HttpStatusCode.NotImplemented)
        }
    }

}
